### ISSUE TITLE
Compose file now working.

### ISSUE THREAD

**Issue by JCSynthTux** [aam-git/dockerfiles#1]
The compose file will not work since there is a tab at line 16.

This worked for me:
```
version: '3.2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_ROOT_PASSWORD=PASSWORD
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  opencart:
    image: aamservices/opencart:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - opencart_data:/var/www/html
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_data:
    driver: local
```
